//Fetch BannerList
export const FETCH_BANNER_LIST = "FETCH_BANNER_LIST";
export const FETCH_BANNER_LIST_SUCCESS = "FETCH_BANNER_LIST_SUCCESS";
export const FETCH_BANNER_LIST_FAIL = "FETCH_BANNER_LIST_FAIL";
export const FETCH_BANNER_LIST_START = "FETCH_BANNER_LIST_START";

//Fetch TopList
export const FETCH_TOPLIST = "FETCH_TOPLIST";
export const FETCH_TOPLIST_START = "FETCH_TOPLIST_START";
export const FETCH_TOPLIST_SUCCESS = "FETCH_TOPLIST_SUCCESS";
export const FETCH_TOPLIST_FAIL = "FETCH_TOPLIST_FAIL";

//Fetch SubList
export const FETCH_SUBLIST = "FETCH_SUBLIST";
export const FETCH_SUBLIST_START = "FETCH_SUBLIST_START";
export const FETCH_SUBLIST_SUCCESS = "FETCH_SUBLIST_SUCCESS";
export const FETCH_SUBLIST_FAIL = "FETCH_SUBLIST_FAIL";

//Fetch RankList
export const FETCH_RANKLIST = "FETCH_RANKLIST";
export const FETCH_RANKLIST_START = "FETCH_RANKLIST_START";
export const FETCH_RANKLIST_SUCCESS = "FETCH_RANKLIST_SUCCESS";
export const FETCH_RANKLIST_FAILED = "FETCH_RANKLIST_FAILED";

//Fetch SearchResult
export const FETCH_SEARCH_RESULT = "FETCH_SEARCH_RESULT";
export const FETCH_SEARCH_RESULT_START = "FETCH_SEARCH_RESULT_START";
export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS";
export const FETCH_SEARCH_RESULT_FAILED = "FETCH_SEARCH_RESULT_FAILED";

//Fetch GoodsDetail
export const FETCH_GOODS_DETAIL = "FETCH_GOODS_DETAIL";
export const FETCH_GOODS_DETAIL_START = "FETCH_GOODS_DETAIL_START";
export const FETCH_GOODS_DETAIL_SUCCESS = "FETCH_GOODS_DETAIL_SUCCESS";
export const FETCH_GOODS_DETAIL_FAILED = "FETCH_GOODS_DETAIL_FAILED";

//Fetch GoodsDetial DealList
export const FETCH_DEALLIST = "FETCH_DEALLIST";
export const FETCH_DEALLIST_START = "FETCH_DEALLIST_START";
export const FETCH_DEALLIST_SUCCESS = "FETCH_DEALLIST_SUCCESS";
export const FETCH_DEALLIST_FAIL = "FETCH_DEALLIST_FAIL";
