//Fetch BannerList
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST'
export const FETCH_BANNER_LIST_SUCCESS = 'FETCH_BANNER_LIST_SUCCESS'
export const FETCH_BANNER_LIST_FAIL = 'FETCH_BANNER_LIST_FAIL'
export const FETCH_BANNER_LIST_START = 'FETCH_BANNER_LIST_START'

//Fetch TopList
export const FETCH_TOPLIST = 'FETCH_TOPLIST'
export const FETCH_TOPLIST_START = 'FETCH_TOPLIST_START'
export const FETCH_TOPLIST_SUCCESS = 'FETCH_TOPLIST_SUCCESS'
export const FETCH_TOPLIST_FAIL = 'FETCH_TOPLIST_FAIL'

//Fetch SubList
export const FETCH_SUBLIST = 'FETCH_SUBLIST'
export const FETCH_SUBLIST_START = 'FETCH_SUBLIST_START'
export const FETCH_SUBLIST_SUCCESS = 'FETCH_SUBLIST_SUCCESS'
export const FETCH_SUBLIST_FAIL = 'FETCH_SUBLIST_FAIL'

//Fetch RankList
export const FETCH_RANKLIST = 'FETCH_RANKLIST'
export const FETCH_RANKLIST_START = 'FETCH_RANKLIST_START'
export const FETCH_RANKLIST_SUCCESS = 'FETCH_RANKLIST_SUCCESS'
export const FETCH_RANKLIST_FAILED = 'FETCH_RANKLIST_FAILED'