//Fetch BannerList
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST'
export const FETCH_BANNER_LIST_SUCCESS = 'FETCH_BANNER_LIST_SUCCESS'
export const FETCH_BANNER_LIST_FAIL = 'FETCH_BANNER_LIST_FAIL'
export const FETCH_BANNER_LIST_START = 'FETCH_BANNER_LIST_START'